### ISSUE TITLE
OSX ENG 2018 zim file crash when launching

### ISSUE THREAD

**Issue by Crapouchinawip** [kiwix/kiwix#513]
Hi, 

I used to have the 2017 ENG zim file opened on KIWIX 0.9 on the same exact offline computer without any problem. I downloaded the 2018 and did trash the 2017 in order to make space on the external disk. The 2018 ENG zim keep crashing on the open using KIWIX 0.9 with the error EXC_CRASH (SIGABRT). For some reason, the FRENCH 2018 version 40 gig is working without any problem. It is located on the same external disk as the English version. 
It seems Kiwix may have decided to let the old OSX version down or what since the 2.0 is not compatible with Lion anymore. The concept of offline and old computer do have a correlation. Second, not letting us know that fact before trashing 2017 is very frustrating. anyway 

Any idea

Thanks,  

Luc

**Comment by kelson42** [comment]
I have transfered to the "kiwix-xulrunner", as this is a ticket about it.

**Comment by kelson42** [comment]
@Crapouchinawip We simply do not support anymore neither OSX lion 10.7.5 nor kiwix-xulrunner. This is why we have now [Kiwix Desktop for MacOS](https://itunes.apple.com/us/app/kiwix-desktop/id1275066656). But you need to upgrade your version of MacOS first... if you can.

We have no secret but it is true we still have communication issue regarding the fact that we have upgraded the ZIM format to be able to store fulltext indexes and that this kind of ZIM files are not easily readable with kiwix-xulrunner 0.8.
